version: "2"
services:
  mysql:
    build: ./docker/mysql/
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes_from:
      - datastore

  rails:
    build:
      context: ./
      dockerfile: ./docker/rails/development/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    volumes_from:
      - datastore
    links:
      - mysql
    environment:
      MYSQL_HOST: mysql
    tty: true
    stdin_open: true

  datastore:
    image: busybox
    volumes:
      - mysql-data:/var/lib/mysql
      - bundle:/usr/local/bundle

volumes:
  mysql-data:
    driver: local
  bundle:
    driver: local
